package com.faster.fasterboot
import com.quantumn.future.DroolsPojo
import java.util.List

query Q (Integer i)
    String( this == i.toString() )
end
rule R @Propagation(IMMEDIATE) when
    $i : Integer()
    ?Q( $i; )
then
    System.out.println( $i );
end

rule "rule1"
when
    $dpojo : DroolsPojo(answers!=null)
    $answersWithoutEmptyStrings : List() from collect ( String(length > 0) from $dpojo.answers )
then
    for (Object answer:$answersWithoutEmptyStrings){
        System.out.println((String)answer);
    }
end

