package com.faster.fasterboot

import com.quantumn.future.model.TradeAuditBo
import com.quantumn.future.model.Trade
import java.math.BigDecimal
import java.util.concurrent.atomic.AtomicLong;

query Q (Integer i)
    String( this == i.toString() )
end
rule R when
    $i : Integer()
    ?Q( $i; )
then
    System.out.println( $i );
end

rule "simplerule"
when
eval(true)
then System.out.println("it is a test");
end

rule "txnaudit"
    //no-loop true
    when
        bo : TradeAuditBo(past24hSuccTradeCnt>5)
    then
        System.out.println("hit rule: past24hSuccTradeCnt>5");
end



declare window Ticks
    Trade()
        over window:length( 10 )
end


rule "txnaudit2"
    when
//        accumulate(Trade(flag=="S") from window Ticks,mycount:count(1))
      Number( intValue == 2 ) from accumulate(Trade(flag=="F") over window:length(5),count(1))
//    Trade() over window:time(5m)
    then
        System.out.println("hit rule:count by slide window");

end

rule "txnaudit3"
when
$trade:Trade();
Trade(flag=="F",this after [0s,10s] $trade)
then
System.out.println("next trade comes in 10s");
 end



