package com.faster.fasterboot

import com.quantumn.future.model.TradeAuditBo
import com.quantumn.future.model.Trade
import java.math.BigDecimal
import java.util.concurrent.atomic.AtomicLong;

rule "txnaudit"
    //no-loop true
    when
        bo : TradeAuditBo(past24hSuccTradeCnt>5)
    then
        System.out.println("hit rule: past24hSuccTradeCnt>5");
end



declare window Ticks
    Trade()
        over window:length( 10 )
end


rule "txnaudit2"
    when
        accumulate(Trade() from window Ticks,mycount:count(1))
//      Number( intValue > 2 ) from accumulate(Trade() over window:length(5),count(1))
//    Trade() over window:time(5m)
    then
        System.out.println("hit rule:count by slide window,value>2:"+mycount);

end

